### ISSUE TITLE
Static library

### ISSUE THREAD

**Issue by ghost** [cygwinports/mingw64-x86_64-expat#1]
Currently only shared library is built:

~~~
usr/x86_64-w64-mingw32/sys-root/mingw/bin/libexpat-1.dll
usr/x86_64-w64-mingw32/sys-root/mingw/lib/libexpat.dll.a
~~~

**Comment by ghost** [comment]
Workaround; static library is available here:

http://repo.msys2.org/mingw/x86_64

Example:

http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-expat-2.2.0-2-any.pkg.tar.xz

**Comment by svnpenn** [comment]
https://github.com/cygwinports/mingw64-x86_64-fdk-aac/issues/1

**Comment by svnpenn** [comment]
https://github.com/cygwinports/mingw64-x86_64-lua/issues/1

**Comment by svnpenn** [comment]
https://github.com/cygwinports/mingw64-x86_64-nghttp2/issues/1

**Comment by svnpenn** [comment]
https://github.com/cygwinports/mingw64-x86_64-pcre/issues/1

**Comment by svnpenn** [comment]
https://github.com/cygwinports/mingw64-x86_64-gnutls/issues/1
